<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مطالعه بازار‌های هدف
</font>
</h1>

   
<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    کتابخانه‌ها
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
       ابتدا کتاب‌خانه‌های مورد نیاز خود را اضافه کنید.    
</font>
</p>

In [8]:
# import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    فایل پیش‌پردازش‌شده را بخوانید.
</font>
</p>

In [9]:
# read the preprocessed dataset
df = pd.read_csv('./preprocessed_sales.csv')
df.head()

,InvoiceNumber,ProductCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerId,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom

![output.png](attachment:00bd86fb-f56f-4110-9232-70e36dec8b93.png)
<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
رسم نمودار پراکندگی میزان فروش و تعداد مشتریان کشورها
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این قسمت بر روی یک نمودار پراکندگی، کشورهای مختلف را نمایش می‌دهید تا میزان فروش و تعداد مشتریان آنها را ببینیم. همانطور که در پایین مشخص شده‌است، کشور‌ها با توجه به میزان فروش و تعداد مشتریان به ۴ گروه تقسیم می‌شوند.
<br>
با استفاده از چارک‌ سوم هر دو معیار، شما با ۴ گروه از کشورها روبه‌رو می‌شوید.
<br>
اگر میزان فروش را را SA و چارک سومش را به qSA، تعداد مشتری‌ها را CC و چارک سومش را با qCC نشان دهیم، ۴ گروه از کشورها به شکل زیر تعریف می‌شوند.
</font>
</p>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
    <font>
        <ol>
            <li>
                کشور‌هایی که در آن‌ها SA < qSA و CC < qCC
            </li>
            <li>
               کشور‌هایی که در آن‌ها SA < qSA و CC > qCC
            </li>
            <li>
               کشور‌هایی که در آن‌ها SA > qSA و CC < qCC
            </li>
            <li>
               کشور‌هایی که در آن‌ها SA > qSA و CC > qCC
            </li>
        </ol>
  </font>
</div>

<br>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
برای رسم نمودار باید مراحل زیر را طی کنید:

<ul dir =rtl>
  <li>
ابتدا سفارشات مربوط به United Kingdom را حذف کنید
</li>

  <li>
به ازای هر کشور، تعداد مشتری و میزان فروش را محاسبه کنید.</li>

  <li>
چارک سوم را برای میزان فروش و تعداد مشتری به دست آورید.</li>

  <li>
با استفاده از توضیحات بالا، کشورها را به چهار گروه تقسیم کنید.
</li>
  <li>
در ادامه، با استفاده از اطلاعاتی که به دست آورده‌اید، نمودار زیر را رسم کنید.
</li>
</ul>

</font>
</p>

<p style="text-align:center;"><img src="output.png"></p>



<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ویژگی‌های نمودار
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<table dir=rtl align = center>

<tr>
<th><font face="vazir" size=3>ویژگی</th>
<th><font face="vazir" size=3>مقدار</th>
</tr>

<tr>
<td><font face="vazir" size=3>اندازه شکل</td>
<td><font face="vazir" size=3>۱۰ در ۱۰ اینچ</td>
</tr>

<tr>
<td><font face="vazir" size=3>رنگ کشورهای گروه اول</td>
<td><font face="vazir" size=3>red</td>
</tr>

<tr>
<td><font face="vazir" size=3>رنگ کشورهای گروه دوم</td>
<td><font face="vazir" size=3>blue</td>
</tr>

<tr>
<td><font face="vazir" size=3>رنگ کشورهای گروه سوم</td>
<td><font face="vazir" size=3>green</td>
</tr>

<tr>
<td><font face="vazir" size=3>رنگ کشورهای گروه چهارم</td>
<td><font face="vazir" size=3>cyan</td>
</tr>

<tr>
<td><font face="vazir" size=3>اندازه فونت عنوان صفحه‌محور</td>
<td><font face="vazir" size=3>۱۸</td>
</tr>

<tr>
<td><font face="vazir" size=3>اندازه فونت محور افقی و عمودی</td>
<td><font face="vazir" size=3>۱۶</td>
</tr>

<tr>
<td><font face="vazir" size=3>اندازه نقاط</td>
<td><font face="vazir" size=3>۲۰</td>
</tr>

<tr>
<td><font face="vazir" size=3>استایل</td>
<td><font face="vazir" size=3>fivethirtyeight</td>
</tr>

</table>
</p>

<h2 dir = rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
نکات مربوط به <code>legend</code>
</font>
</h2>
<p dir=rtl align=right style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<code>legend</code> این نمودار کمی با نمونه‌هایی که پیش از این دیدید فرق دارد. در اینجا، <code>legend</code> استفاده شده دارای عنوان و قاب می‌باشد. عنوان <code>legend</code> با استفاده از پارامتر  <code>title</code> انتخاب می‌شود. با <code>True</code> کردن پارامتر <code>frameon</code> قاب برای <code>legend</code> نمایش داده می‌شود.
<br>
برای تغییر اندازه فونت عنوان و رنگ زمینه قاب، از پارامترهای <code>title_fontsize</code> و <code>facecolor</code> استفاده کنید.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" color="#0099cc">
ویژگی‌های <code>legend</code>
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<table dir=rtl align = center>

<tr>
<th><font face="vazir" size=3>ویژگی</th>
<th><font face="vazir" size=3>مقدار</th>
</tr>

<tr>
<td><font face="vazir" size=3>رنگ زمینه قاب</td>
<td><font face="vazir" size=3>silver</td>
</tr>

<tr>
<td><font face="vazir" size=3>اندازه فونت عنوان</td>
<td><font face="vazir" size=3>۱۶</td>
</tr>

<tr>
<td><font face="vazir" size=3>اندازه فونت متون</td>
<td><font face="vazir" size=3>۱۴</td>
</tr>

</table>
</p>

<p dir=rtl align=right style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در انتها،‌ کشورهای فرانسه، اسپانیا و هلند را روی نقشه نمایش دهید. یعنی،‌ نام آنها را روی نقاطی که این کشورها را نشان می‌دهند، رسم کنید. موقعیت متون، همان موقعیت نقاط کشورها می‌باشد با این تفاوت که در محور عمودی، موقعیت متن‌ها نیم واحد افزایش یافته است. اندازه فونت این متن‌ها، ۱۵ می‌باشد.

</font>
</p>

In [91]:
# prepare the dataframe
df = df[df['Country'] != 'United Kingdom']
df.head(10)
df['mul'] = df['UnitPrice'] * df['Quantity']
number = pd.DataFrame(df.groupby('Country')['CustomerId'].nunique())
Q3_number = float(number.quantile(0.75))
number['revenue'] = pd.DataFrame(df.groupby('Country')['mul'].sum())
Q3_revenue = float(number['revenue'].quantile(0.75))

first = number[(number.revenue < Q3_revenue) & (number.CustomerId < Q3_number)]
second = number[(number.revenue < Q3_revenue) & (number.CustomerId > Q3_number)]
third = number[(number.revenue > Q3_revenue) & (number.CustomerId < Q3_number)]
forth = number[(number.revenue > Q3_revenue) & (number.CustomerId > Q3_number)]
forth

             CustomerId     revenue
Country
Australia            15   31446.800
France               47  146107.070
Germany              67  202025.391
Netherlands          22  268784.350
Spain                25   47568.650
Sweden               16   53147.990
Switzerland          14   43921.390

In [98]:
# plot
sns.set_style()
plt.style.use('fivethirtyeight')
fig , ax = plt.subplots(figsize = (10,10))

ax.scatter(forth['revenue'],forth['CustomerId'],label = 'Highest customer & revenue',marker = 'o' ,s = 20, c = 'red')
ax.scatter(second['revenue'],second['CustomerId'],label = 'High customer & low revenue',marker = 'o' ,s = 20, c = 'blue')
ax.scatter(third['revenue'],third['CustomerId'],label = 'High revenue & low customer',marker = 'o' ,s = 20, c = 'green')
ax.scatter(first['revenue'],first['CustomerId'],label = 'Low customer & revenue',marker = 'o' ,s = 20, c ='cyan')

ax.legend(title = 'Group',frameon = True,fontsize = 14 ,title_fontsize = 16, facecolor = 'silver')

ax.set_title('Market Study', size = 18)
ax.set_xlabel('Sales amount', size = 16)
ax.set_ylabel('Number of customers', size = 16)

ax.text(146107.070,47.5, 'France', fontsize = 15)
ax.text(268784.350,22.5 'Netherlands', fontsize = 15)
ax.text(47568.650,25.5, 'Spain', fontsize = 15)

SyntaxError: invalid syntax (Temp/ipykernel_9896/1682998453.py, line 18)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سلول جواب‌ساز    
</font>
</h2>

In [87]:

import zipfile
import joblib

joblib.dump(fig,"fig")


def compress(file_names):
    print("File Paths:")
    print(file_names)
    # Select the compression mode ZIP_DEFLATED for compression
    # or zipfile.ZIP_STORED to just store the file
    compression = zipfile.ZIP_DEFLATED
    # create the zip file first parameter path/name, second mode
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            # Add file to the zip file
            # first parameter file to zip, second filename in zip
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ["fig", "3_market_study.ipynb"]
compress(file_names)

File Paths:
['fig', '3_market_study.ipynb']