<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ارزش‌گذاری مشتریان
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    توضیحات اولیه
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font>
    در ادامه امور مربوط به بازاریابی، شما بایستی که اقدام به گروه‌بندی مشتریان بر اساس ارزش ‌آنها برای شرکت "سیب" بکنید. بدین منظور از روش معروف حوزه تحلیل رفتار مشتری با نام <a href="https://en.wikipedia.org/wiki/RFM_(market_research)">RFM</a> استفاده خواهید کرد. طبق این روش، سه معیار زیر برای هر مشتری مد‌نظر قرار می‌گیرد.
</font>
</p>


<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font>
    <ul>
        <li>
            معیار Recency (ماندگاری) : تعداد روزی که از آخرین خرید مشتری می گذرد.
        </li>
        <li>
            معیار Frequency (فرکانس) : تعداد دفعاتی که مشتری از ما خرید کرده‌است.
        </li>
        <li>
            معیار Monetary value (ارزش مالی) : مجموع درآمدی که شرکت از یک مشتری داشته‌است.
        </li>
    </ul>
</font>
</div>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font> 
این معیارها، نشانگر شاخص‌های مهمی در رفتار مشتریان می‌باشند. به عنوان مثال، هرچه خرید جدیدتر صورت گرفته‌باشد، احتمال این که مشتری دوباره خرید کند، افزایش می‌یابد. هرچه مشتری تعداد دفعات بیشتری خرید کند یعنی مشتری رضایت بیشتری دارد و میزان درآمدی که یک مشتری برای شرکت تولید می کند، می‌تواند او را از خریداران دیگر متمایز کند.
    <br>
    در این مرحله، شما بایستی که برای هر مشتری (CustomerId)، این سه معیار را محاسبه کنید. توجه داشته‌باشید که برای محاسبه معیار Recency، تعداد روز گذشته نسبت به یک روز بعد از آخرین روز موجود در دادگان را محاسبه کنید (با این فرض که شما در آن روز، در حال انجام این مرحله هستید).
    <br>
    بعد از محاسبه این سه معیار، مقدار (value‍‍) هر معیار را بر اساس چارک اول، دوم و سوم به شکل زیر به ۴ گروه تقسیم کنید.
</font>
</p>

<div dir=rtl style="direction: ltr;text-align: left;line-height:200%;font-family:vazir;font-size:medium">
<font>
    <ul>
        <li><b>Group1</b>: value <= Q1</li>
        <li><b>Group2</b>: Q1 &lt; value <= Q2</li>
        <li><b>Group3</b>: Q2 &lt; value <= Q3</li>
        <li><b>Group4</b>: Q3 &lt; value</li>
    </ul>
</font>
</div>



<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font> 
    برای یادآوری مفهوم چارک،
    <a href="https://fa.wikipedia.org/wiki/%DA%86%D8%A7%D8%B1%DA%A9_(%D8%A2%D9%85%D8%A7%D8%B1)">اینجا</a>
    را از ویکی‌پدیای فارسی بخوانید.
    <br>
    با استفاده از این سه معیار، ارزش هر مشتری (معیار RFM)، با کنار هم قرار دادن گروه‌های Recency-Frequency-Monetary value محاسبه می‌گردد. به عنوان مثال، به نمونه‌های زیر نگاه کنید.
</font>
</p>


<div dir=rtl style="direction: ltr;text-align: left;line-height:200%;font-family:vazir;font-size:medium">
<font>
    
| CustomerID | Recency | Frequency | Monetary value| R_quartile      | F_quartile      | M_quartile      | RFM    |
| ---------- | ------- | --------- | -------- | ------ | ------ | ------ | ------ |
| 12346      | 325     | 1         | 77183.60 | 1      | 1      | 4      | 114    |
| 12347      | 2       | 182       | 4310.00  | 4      | 4      | 4      | 444    |
| 12348      | 75      | 31        | 1797.24  | 2      | 2      | 4      | 224    |
</font>
</div>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font> 
    مشتری با شناسه ۱۲۳۴۶، Recency برابر با ۳۲۵ داشته است. عدد ۳۲۵ کوچک‌تر یا مساوی چارک اول Recencyها بوده‌است. (در این جدول ما نمی‌دانیم چارک‌ها چه مقداری داشته‌اند. چیزی که برای ما حائز اهمیت است، آن است که بتوانیم گروهی که Recency این مشتری به آن تعلق دارد را شناسایی کنیم.)
    <br>
    چون از چارک اول کوچک‌تر یا مساوی بوده‌است، طبق <b>Group1</b>: value <= Q1 ، برای Recency این مشتری عدد ۱ را در نظر می‌گیریم (زیرا به گروه یک تعلق دارد.)
<br>
    برای دو مقدار دیگر (Frequency و Monetary value) نیز طبق بالا عمل می‌کنیم تا گروه آن‌ها را به دست بیاوریم.
    <br>
       حال شماره گروه هر سه معیار را کنار هم‌دیگر می‌گذاریم تا معیار RFM به‌وجود بیاید.
    <br>
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font> 
حال شما، می توانید هر مشتری را طبق جدول زیر و بر اساس مقدار RFM، گروه‌بندی کنید.
</font>
</p>



<div dir=rtl style="direction: ltr;text-align: left;line-height:200%;font-family:vazir;font-size:medium">
<font>
    
| Segment | RFM |
|:-------------:|:------|
| Best | 144 |
| AlmostLost | 344 |  
| LostBigSpenders | 444  | 
| LostCheap | 441 |
| Loyal | X4X | 
| BigSpenders | XX4 | 


</font>
</div>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font>
توجه داشته‌باشید که مقدار X به معنی هر مقدار معتبری می‌باشد. به عنوان مثال، 14X شامل گروه‌های 141, 142, 143, 144 می‌شود. همچنین اگر یک RFM در دو گروه از جدول می‌تواند قرار بگیرد، اولویت با گروهی‌ است که ابتدا (بالاتر) در جدول آمده‌باشد. در صورتی که یک مشتری در هیچ‌یک از گروه‌های جدول قرار نگرفت، گروه او را Normal‌ اعلام کنید.
    <br>
در نتیجه، به ازای هر مشتری، تیم بازاریابی می تواند استراتژی متناسب با گروهی‌ که او در آن قرار می‌گیرد، اتخاذ کند.   
    <br>
    برای هر مشتری، ستون Segment را طبق جدول توضیح داده شده در بالا محاسبه کنید. در آخر دیتافریمی تنها با دو ستون CustomerId و Segment در متغیر <code>df_customer_segments</code> ذخیره کنید.
</font>
</p>

   
<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    کتابخانه‌ها
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
       ابتدا کتاب‌خانه‌های مورد نیاز خود را اضافه کنید.    
</font>
</p>

In [124]:
# import libraries: TODO
import pandas as pd
from datetime import timedelta


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    فایل پیش‌پردازش‌شده را بخوانید.
</font>
</p>

In [125]:
# read the preprocessed dataset: TODO
df = pd.read_csv('preprocessed_sales.csv')
df

,InvoiceNumber,ProductCode,ProductName,Quantity,InvoiceDate,UnitPrice,CustomerId,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom
...,...,...,...,...,...,...,...,...
400911,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530,United Kingdom
400912,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530,United Kingdom
400913,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530,United Kingdom
400914,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530,United Kingdom
400915,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530,United Kingdom

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
معیارهای Frequency، Recency و Monetary value را به ازای هر مشتری محاسبه کنید و دیتافریم <code>df_customer_segments</code> را مقداردهی کنید.
</font>
</p>

In [153]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['totalSum'] = df['Quantity'] * df['UnitPrice']
recent_date = max(df['InvoiceDate']) + timedelta(days = 1)
data_process = df.groupby('CustomerId', as_index = False).agg({
    'InvoiceDate' : lambda x:(recent_date - x.max()).days,
    'InvoiceNumber' : 'count',
    'totalSum' : 'sum'})
data_process.rename(columns = {'InvoiceDate' : 'Recency', 'InvoiceNumber' : 'Frequency', 'totalSum' : 'Monetary value'}, inplace = True) 

quantiles = data_process[['Recency','Frequency','Monetary value']].quantile([0.25,0.5,0.75]).to_dict()

def rfm_group(x,c):
    if x <=  quantiles[c][0.25]:
        return 1
    elif ( x > quantiles[c][0.25]) & (x <=  quantiles[c][0.5]):
        return 2
    elif (x > quantiles[c][0.5]) & (x <=  quantiles[c][0.75]):
        return 3
    elif x >=  quantiles[c][0.75]:
        return 4
data_process['R'] = data_process['Recency'].apply(lambda x: rfm_group(x,'Recency'))
data_process['F'] = data_process['Frequency'].apply(lambda x: rfm_group(x,'Frequency'))
data_process['M'] = data_process['Monetary value'].apply(lambda x: rfm_group(x,'Monetary value'))


data_process['RFM'] = data_process['R'].map(str) + data_process['F'].map(str) + data_process['M'].map(str)
data_process


segt_map = {
    r'144': 'Best',
    r'344': 'AlmostLost',
    r'444': 'LostBigSpenders',
    r'441': 'LostCheap',
    r'[1-4]4[1-4]': 'Loyal',
    r'[1-4][1-4]4': 'BigSpenders',
    r'[1-4][1-4][1-4]': 'Normal'
}
data_process['Segment'] = data_process['R'].map(str) +  data_process['F'].map(str) + data_process['M'].map(str)     
data_process['Segment'] = data_process['Segment'].replace(segt_map, regex=True)  

df_customer_segments = data_process.drop(['Recency','Frequency','Monetary value','R','F','M','RFM'], axis = 1)
df_customer_segments

      CustomerId      Segment
0          12346       Normal
1          12347       Normal
2          12348       Normal
3          12349        Loyal
4          12351       Normal
...          ...          ...
4307       18283        Loyal
4308       18284       Normal
4309       18285       Normal
4310       18286       Normal
4311       18287  BigSpenders

[4312 rows x 2 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سلول جواب‌ساز    
</font>
</h2>

In [127]:
# export your results

import zipfile
import joblib

df_customer_segments.to_csv('./df_customer_segments.csv', index=False)

def compress(file_names):
    print("File Paths:")
    print(file_names)
    # Select the compression mode ZIP_DEFLATED for compression
    # or zipfile.ZIP_STORED to just store the file
    compression = zipfile.ZIP_DEFLATED
    # create the zip file first parameter path/name, second mode
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            # Add file to the zip file
            # first parameter file to zip, second filename in zip
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ["df_customer_segments.csv", "rfm.ipynb"]
compress(file_names)

File Paths:
['df_customer_segments.csv', 'rfm.ipynb']